### PR TITLE
Add DigitalOcean logo to website

### PR DESCRIPTION
**Pull request by tekknolagi**

### CODE REVIEW

**Comment by bsteephenson** [comment]
I'll add it to the page. Should it belong with the silver, gold, or bronze sponsors?

**Comment by bsteephenson** [comment]
Web
image

Mobile
image

The logo is more square than the others so it looks bigger on mobile

**Comment by anontesting** [comment]
You have to use xs cols too (I think). Check how we did it with blue apron. Can you put it in the same row as blue apron too?

**Comment by anontesting** [comment]
Sorry this is Richard, logged into wrong account t

**Comment by bsteephenson** [comment]
image

image

Used a different logo. More rectangular

**Comment by bsteephenson** [comment]
image

image

Used a different logo (more rectangular)

**Comment by tekknolagi** [comment]
@cwRichardKim is this OK to merge?

**Comment by cwRichardKim** [comment]
Can some slight CSS be applied to adjust the vertical position?

**Comment by cwRichardKim** [comment]
Else lgtm

**Comment by bsteephenson** [comment]
image

Done'd manually with upper padding. Let someone else manually fiddle it to make it perfect (or use flexbox like sane people)

**Pull request merged**
